"""Generate/check the frozen user API contract consumed by the frontend."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from api_errors import ERROR_CODES
from main import app


ROOT = Path(__file__).resolve().parents[2]
JSON_TARGET = ROOT / "contracts" / "user-api-v1.json"
TS_TARGET = ROOT / "frontend" / "src" / "api" / "user-api-v1.generated.ts"
AUTH_PATHS = {
    "/api/auth/login",
    "/api/auth/me",
    "/api/auth/users",
    "/api/auth/users/{user_id}",
    "/api/auth/change-password",
}


def build_snapshot() -> dict:
    schema = app.openapi()
    paths = {path: schema["paths"][path] for path in sorted(AUTH_PATHS)}
    referenced = set()
    encoded = json.dumps(paths, sort_keys=True)
    for name in schema.get("components", {}).get("schemas", {}):
        if f"#/components/schemas/{name}" in encoded:
            referenced.add(name)
    # Include one level of nested schema references (UserSummary -> MembershipSummary).
    components = schema.get("components", {}).get("schemas", {})
    changed = True
    while changed:
        changed = False
        selected = json.dumps({name: components[name] for name in referenced}, sort_keys=True)
        for name in components:
            if name not in referenced and f"#/components/schemas/{name}" in selected:
                referenced.add(name)
                changed = True
    return {
        "contract_version": schema["info"]["x-api-contract-version"],
        "error_codes": {str(status): code for status, code in sorted(ERROR_CODES.items())},
        "paths": paths,
        "schemas": {name: components[name] for name in sorted(referenced)},
    }


def render_json(snapshot: dict) -> str:
    return json.dumps(snapshot, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_ts(snapshot: dict) -> str:
    payload = json.dumps(snapshot, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by backend/scripts/export_user_contract.py; do not edit.\n"
        f"export const USER_API_V1_SNAPSHOT = {payload} as const;\n"
        "export type ApiErrorCode = typeof USER_API_V1_SNAPSHOT.error_codes[keyof "
        "typeof USER_API_V1_SNAPSHOT.error_codes];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    snapshot = build_snapshot()
    expected = {JSON_TARGET: render_json(snapshot), TS_TARGET: render_ts(snapshot)}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, value in expected.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != value]
        if stale:
            raise SystemExit("User API contract snapshot is stale: " + ", ".join(stale))
        return 0
    for path, value in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
